name: Deploy Admin Frontend Next.js

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/irelis-admin-front:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/irelis-admin-front:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop and remove old container
        run: docker rm -f irelis-admin-front || true

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/irelis-admin-front:latest

      - name: Run new container
        run: |
          docker run -d \
            --name irelis-admin-front \
            -p 3000:3000 \
            -e NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }} \
            ${{ secrets.DOCKER_USERNAME }}/irelis-admin-front:latest
