name: Deploy Admin Frontend Next.js

on:
  push:
    branches:
      - reuse-initial-job-preview-dialog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: reuse-initial-job-preview-dialog

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/irelis-admin:server .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/irelis-admin:server

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Stop and remove all containers
        run: docker ps -aq | xargs -r docker rm -f

      - name: Remove all images
        run: docker images -q | xargs -r docker rmi -f

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/irelis-admin:server

      - name: Run new container
        run: |
          docker run -d \
            --name irelis-admin-front \
            -e PORT=3001 \
            -p 3001:3001 \
            -e NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }} \
            ${{ secrets.DOCKER_USERNAME }}/irelis-admin:server

